#!/bin/sh

while read remote_ref
do
  if [[ "$remote_ref" =~ refs/heads/(main|master|staging)$ ]]; then
    echo "Running ruff check for $remote_ref"
    ruff check --exit-non-zero-on-fix
  else
    echo "No linting for branch $remote_ref"
    continue
  fi

  RUFF_EXIT_CODE=$?

  if [ $RUFF_EXIT_CODE -ne 0 ]; then
    echo "ruff check reported linting issues on branch $remote_ref"
    exit $RUFF_EXIT_CODE
  fi
done

exit 0