#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
    if [[ "$remote_ref" =~ refs/heads/(main|master|staging)$ ]]; then
        echo "Running ruff check for $remote_ref"
        ruff check --exit-non-zero-on-fix

        RUFF_EXIT_CODE=$?

        if [ $RUFF_EXIT_CODE -ne 0 ]; then
            echo "ruff check reported linting issues on branch $remote_ref"
            exit $RUFF_EXIT_CODE
        fi
    else
        echo "No linting for branch $remote_ref"
        continue
    fi

done

exit 0